experimental-features = nix-command flakes
restrict-eval = true
allowed-uris = https://cache.nixos.org https://github.com/NixOS/nixpkgs https://nixos.org
sandbox = true
flake-registry = /etc/nix/registry.json
build-users-group = 
trusted-users = root copilot
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = true
